import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Background from "./components/Background";
import Particles from "./components/Particles";
import { ThemeProvider } from "./context/ThemeContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Leandro Villalba",
  description: "Generated by Leandro Villalba",

};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${montserrat.className} `}>
        <ThemeProvider>
          <Background />
          {/* <Particles /> */}

          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}